if we don't have libtermcap, try to use libcurses

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3877,7 +3877,7 @@ else
 fi
 
 
-  echo "$as_me:$LINENO: checking for main in -ltermcap" >&5
+    echo "$as_me:$LINENO: checking for main in -ltermcap" >&5
 echo $ECHO_N "checking for main in -ltermcap... $ECHO_C" >&6
 if test "${ac_cv_lib_termcap_main+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -3987,13 +3987,68 @@ else
 fi
 
   else
-    echo "$as_me:$LINENO: checking for main in -lreadline" >&5
+    echo "$as_me:$LINENO: checking for main in -lcurses" >&5
+echo $ECHO_N "checking for main in -lcurses... $ECHO_C" >&6
+if test "${ac_cv_lib_curses_main+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lcurses  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+
+int
+main ()
+{
+main ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_curses_main=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_curses_main=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_curses_main" >&5
+echo "${ECHO_T}$ac_cv_lib_curses_main" >&6
+if test $ac_cv_lib_curses_main = yes; then
+  CURSES="yes"
+else
+  CURSES="no"
+fi
+
+    if test "x${CURSES}" = "xyes"; then
+      echo "$as_me:$LINENO: checking for main in -lreadline" >&5
 echo $ECHO_N "checking for main in -lreadline... $ECHO_C" >&6
 if test "${ac_cv_lib_readline_main+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   ac_check_lib_save_LIBS=$LIBS
-LIBS="-lreadline -lhistory $LIBS"
+LIBS="-lreadline -lhistory -lcurses $LIBS"
 cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 /* confdefs.h.  */
@@ -4041,6 +4096,9 @@ else
   READLINE="no"
 fi
 
+    else
+      READLINE="no"
+    fi
   fi
   if test "x${READLINE}" = "xyes"; then
     C_FLAGS="${C_FLAGS} -DHAVE_READLINE"
@@ -4052,6 +4110,8 @@ fi
     fi
     if test "x${TERMCAP}" = "xyes"; then
       GETDP_LIBS="${GETDP_LIBS} -ltermcap"
+    else
+      GETDP_LIBS="${GETDP_LIBS} -lcurses"
     fi
   fi
 fi
