petsc 3 configure patch from mark.van.doesburg@technolution.nl

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4182,12 +4182,42 @@ else
   PETSC="no"
 fi
 
-  if test "x${PETSC}" = "xno"; then
-    { { echo "$as_me:$LINENO: error: Could not find PETSC. Use --enable-sparskit instead?" >&5
+  if test "x${PETSC}" = "xyes"; then
+    PETSC_INCLUDE_MAKEFILE='include ${PETSC_DIR}/bmake/common/variables'
+  else
+    as_ac_File=`echo "ac_cv_file_${PETSC_DIR}/${PETSC_ARCH}/include/petscconf.h" | $as_tr_sh`
+{ echo "$as_me:$LINENO: checking for ${PETSC_DIR}/${PETSC_ARCH}/include/petscconf.h" >&5
+echo $ECHO_N "checking for ${PETSC_DIR}/${PETSC_ARCH}/include/petscconf.h... $ECHO_C" >&6; }
+if { as_var=$as_ac_File; eval "test \"\${$as_var+set}\" = set"; }; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  test "$cross_compiling" = yes &&
+  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+if test -r "${PETSC_DIR}/${PETSC_ARCH}/include/petscconf.h"; then
+  eval "$as_ac_File=yes"
+else
+  eval "$as_ac_File=no"
+fi
+fi
+ac_res=`eval echo '${'$as_ac_File'}'`
+	       { echo "$as_me:$LINENO: result: $ac_res" >&5
+echo "${ECHO_T}$ac_res" >&6; }
+if test `eval echo '${'$as_ac_File'}'` = yes; then
+  PETSC="yes"
+else
+  PETSC="no"
+fi
+
+    if test "x${PETSC}" = "xyes"; then
+      PETSC_INCLUDE_MAKEFILE='include ${PETSC_DIR}/conf/variables'
+    else
+      { { echo "$as_me:$LINENO: error: Could not find PETSC. Use --enable-sparskit instead?" >&5
 echo "$as_me: error: Could not find PETSC. Use --enable-sparskit instead?" >&2;}
    { (exit 1); exit 1; }; }
+    fi
   fi
-  PETSC_INCLUDE_MAKEFILE='include ${PETSC_DIR}/bmake/common/variables'
   LAPACK="yes"
   LINKER="\${CLINKER}"
   FLAGS="${FLAGS} -DHAVE_PETSC \${PETSCFLAGS} \${PETSC_INCLUDE}"
