getdp2

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4094,6 +4094,36 @@ echo "$as_me: error: Could not determine PETSC_DIR. Run configure again with --w
 echo "$as_me: error: Could not determine PETSC_ARCH. Run configure again with --with-petsc-arch." >&2;}
    { (exit 1); exit 1; }; }
   fi
+  as_ac_File=`echo "ac_cv_file_${PETSC_DIR}/bmake/${PETSC_ARCH}/petscconf.h" | $as_tr_sh`
+{ echo "$as_me:$LINENO: checking for ${PETSC_DIR}/bmake/${PETSC_ARCH}/petscconf.h" >&5
+echo $ECHO_N "checking for ${PETSC_DIR}/bmake/${PETSC_ARCH}/petscconf.h... $ECHO_C" >&6; }
+if { as_var=$as_ac_File; eval "test \"\${$as_var+set}\" = set"; }; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  test "$cross_compiling" = yes &&
+  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+if test -r "${PETSC_DIR}/bmake/${PETSC_ARCH}/petscconf.h"; then
+  eval "$as_ac_File=yes"
+else
+  eval "$as_ac_File=no"
+fi
+fi
+ac_res=`eval echo '${'$as_ac_File'}'`
+	       { echo "$as_me:$LINENO: result: $ac_res" >&5
+echo "${ECHO_T}$ac_res" >&6; }
+if test `eval echo '${'$as_ac_File'}'` = yes; then
+  PETSC="yes"
+else
+  PETSC="no"
+fi
+
+  if test "x${PETSC}" = "xno"; then
+    { { echo "$as_me:$LINENO: error: Could not find PETSC. Use --enable-sparskit instead?" >&5
+echo "$as_me: error: Could not find PETSC. Use --enable-sparskit instead?" >&2;}
+   { (exit 1); exit 1; }; }
+  fi
   LAPACK="yes"
   PETSC_INCLUDE_MAKEFILE='include ${PETSC_DIR}/bmake/common/variables'
   GETDP_LIBS+=' ${PETSC_KSP_LIB}'
