- Merged patch from <ohyeahq@yahoo.co.jp> (Lanczos using GSL+Lapack) - Reworked some of Andre's comments in Lanczos.c

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -858,6 +858,8 @@ Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
   --with-gsl-prefix=PFX   prefix where GSL is installed
+  --with-lapack-prefix=PFX
+                          prefix where BLAS/LAPACK is installed
   --with-readline-prefix=PFX
                           prefix where GNU readline is installed
   --with-petsc-prefix=PFX prefix where PETSc is installed
@@ -1290,6 +1292,14 @@ if test "${with_gsl_prefix+set}" = set; then
   GSL_PREFIX=$withval
 else
   GSL_PREFIX="${GSL_DIR}"
+fi;
+
+# Check whether --with-lapack-prefix or --without-lapack-prefix was given.
+if test "${with_lapack_prefix+set}" = set; then
+  withval="$with_lapack_prefix"
+  LAPACK_PREFIX=$withval
+else
+  LAPACK_PREFIX="${LAPACK_DIR}"
 fi;
 
 # Check whether --with-readline-prefix or --without-readline-prefix was given.
@@ -2338,7 +2348,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:2341:" \
+echo "$as_me:2351:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -3150,6 +3160,132 @@ fi
     { { echo "$as_me:$LINENO: error: Could not find GSL, aborting." >&5
 echo "$as_me: error: Could not find GSL, aborting." >&2;}
    { (exit 1); exit 1; }; }
+  fi
+fi
+
+if test "x${GSL}" = "xyes"; then
+  if test "x${LAPACK_PREFIX}" != "x"; then
+    LDFLAGS="-L${LAPACK_PREFIX} ${LDFLAGS}"
+  fi
+
+echo "$as_me:$LINENO: checking for main in -lblas" >&5
+echo $ECHO_N "checking for main in -lblas... $ECHO_C" >&6
+if test "${ac_cv_lib_blas_main+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lblas  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+
+int
+main ()
+{
+main ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_blas_main=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_blas_main=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_blas_main" >&5
+echo "${ECHO_T}$ac_cv_lib_blas_main" >&6
+if test $ac_cv_lib_blas_main = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBBLAS 1
+_ACEOF
+
+  LIBS="-lblas $LIBS"
+
+fi
+
+  echo "$as_me:$LINENO: checking for main in -llapack" >&5
+echo $ECHO_N "checking for main in -llapack... $ECHO_C" >&6
+if test "${ac_cv_lib_lapack_main+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-llapack  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+
+int
+main ()
+{
+main ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_lapack_main=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_lapack_main=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_lapack_main" >&5
+echo "${ECHO_T}$ac_cv_lib_lapack_main" >&6
+if test $ac_cv_lib_lapack_main = yes; then
+  LAPACK="yes"
+else
+  LAPACK="no"
+fi
+
+  if test "x${LAPACK}" = "xyes"; then
+    C_FLAGS="${C_FLAGS} -DHAVE_LAPACK"
+    if test "x${LAPACK_PREFIX}" = "x"; then
+      GETDP_LIBS="${GETDP_LIBS} -llapack -lblas"
+    else
+      GETDP_LIBS="${GETDP_LIBS} -L${LAPACK_PREFIX} -llapack -lblas"
+    fi
   fi
 fi
 
