- reintroduced zitsol - tests for stochastic stuff

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1230,6 +1230,7 @@ Optional Features:
   --enable-cygwin         use the Cygwin library on Windows (default=no)
   --enable-gsl            use GSL as numerical toolkit (default=yes)
   --enable-arpack         enable built-in Arpack eigensolver (default=yes)
+  --enable-zitsol         enable support for ZITSOL (default=no)
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -1725,6 +1726,11 @@ fi
 # Check whether --enable-arpack was given.
 if test "${enable_arpack+set}" = set; then
   enableval=$enable_arpack;
+fi
+
+# Check whether --enable-zitsol was given.
+if test "${enable_zitsol+set}" = set; then
+  enableval=$enable_zitsol;
 fi
 
 
@@ -4317,6 +4323,37 @@ fi
         GETDP_LIBS="${GETDP_LIBS} -llapack -lblas"
       fi
     fi
+  fi
+fi
+
+if test "x$enable_zitsol" = "xyes" -a "x${PETSC}" = "xyes"; then
+  { echo "$as_me:$LINENO: checking for ./contrib/ZITSOL_1/zarms2.c" >&5
+echo $ECHO_N "checking for ./contrib/ZITSOL_1/zarms2.c... $ECHO_C" >&6; }
+if test "${ac_cv_file___contrib_ZITSOL_1_zarms2_c+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  test "$cross_compiling" = yes &&
+  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+if test -r "./contrib/ZITSOL_1/zarms2.c"; then
+  ac_cv_file___contrib_ZITSOL_1_zarms2_c=yes
+else
+  ac_cv_file___contrib_ZITSOL_1_zarms2_c=no
+fi
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_file___contrib_ZITSOL_1_zarms2_c" >&5
+echo "${ECHO_T}$ac_cv_file___contrib_ZITSOL_1_zarms2_c" >&6; }
+if test $ac_cv_file___contrib_ZITSOL_1_zarms2_c = yes; then
+  ZITSOL="yes"
+else
+  ZITSOL="no"
+fi
+
+  if test "x${ZITSOL}" = "xyes"; then
+    FLAGS="${FLAGS} -DHAVE_ZITSOL"
+    GETDP_DIRS="${GETDP_DIRS} contrib/ZITSOL_1"
+    GETDP_LIBS="${GETDP_LIBS} -lGetDPzitsol"
   fi
 fi
 
