don't check for blas/lapack if we use petsc (since petsc requires blas and lapack anyway)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1340,9 +1340,7 @@ fi;
 # Check whether --with-petsc-prefix or --without-petsc-prefix was given.
 if test "${with_petsc_prefix+set}" = set; then
   withval="$with_petsc_prefix"
-  PETSC_PREFIX=$withval
-else
-  PETSC_PREFIX="${PETSC_DIR}"
+  PETSC_DIR=$withval
 fi;
 
 # Check whether --with-petsc-arch or --without-petsc-arch was given.
@@ -2430,7 +2428,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:2433:" \
+echo "$as_me:2431:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -3025,55 +3023,32 @@ fi
 
 
 GETDP_DIRS="Main Parser Post Function Integration GeoData DofData Numeric DataStr FMM"
-GETDP_LIBS="-Llib -lMain -lParser -lPost -lFunction -lIntegration -lGeoData -lDofData -lNumeric -lSparskit -lDataStr -lFMM"
 
 if test "x$enable_petsc" = "xyes"; then
 
-  GETDP_LIBS='-Llib -lMain -lParser -lPost -lFunction -lIntegration -lGeoData -lDofData -lNumeric -lDataStr -lFMM ${PETSC_SLES_LIB} ${PETSC_KSP_LIB} -lm'
-  SOLVER='-DHAVE_PETSC ${PETSCFLAGS} ${PETSC_INCLUDE}'
-  LINKER='${CLINKER}'
-  if test "x${PETSC_PREFIX}" != "x"; then
-    PETSC_DIR="${PETSC_PREFIX}"
-  fi
-  PETSC_INCLUDE_MAKEFILE='include ${PETSC_DIR}/bmake/common/variables'
-  if test "x${PETSC_ARCH}" = "x"; then
-    as_ac_File=`echo "ac_cv_file_${PETSC_DIR}/bin/petscarch" | $as_tr_sh`
-echo "$as_me:$LINENO: checking for ${PETSC_DIR}/bin/petscarch" >&5
-echo $ECHO_N "checking for ${PETSC_DIR}/bin/petscarch... $ECHO_C" >&6
-if eval "test \"\${$as_ac_File+set}\" = set"; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  test "$cross_compiling" = yes &&
-  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
-echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+  if test "x${PETSC_DIR}" = "x"; then
+    { { echo "$as_me:$LINENO: error: Could not determine PETSC_DIR. Run configure again with --with-petsc-prefix." >&5
+echo "$as_me: error: Could not determine PETSC_DIR. Run configure again with --with-petsc-prefix." >&2;}
    { (exit 1); exit 1; }; }
-if test -r "${PETSC_DIR}/bin/petscarch"; then
-  eval "$as_ac_File=yes"
-else
-  eval "$as_ac_File=no"
-fi
-fi
-echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_File'}'`" >&5
-echo "${ECHO_T}`eval echo '${'$as_ac_File'}'`" >&6
-if test `eval echo '${'$as_ac_File'}'` = yes; then
-  OLD_PETSC="yes"
-else
-  OLD_PETSC="no"
-fi
-
-    if test "x${OLD_PETSC}" = "xyes"; then
-      PETSC_ARCH=`${PETSC_DIR}/bin/petscarch`
-    else
-      { { echo "$as_me:$LINENO: error: Could not determine PETSC_ARCH. Run configure again with --with-petsc-arch." >&5
+  fi
+  if test "x${PETSC_ARCH}" = "x"; then
+    { { echo "$as_me:$LINENO: error: Could not determine PETSC_ARCH. Run configure again with --with-petsc-arch." >&5
 echo "$as_me: error: Could not determine PETSC_ARCH. Run configure again with --with-petsc-arch." >&2;}
    { (exit 1); exit 1; }; }
-    fi
   fi
+
+  C_FLAGS="${C_FLAGS} -DHAVE_LAPACK"
+  GETDP_DIRS="${GETDP_DIRS} Arpack"
+  GETDP_LIBS='-Llib -lMain -lParser -lPost -lFunction -lIntegration -lGeoData -lDofData -lNumeric -lDataStr -lFMM -lArpack ${PETSC_KSP_LIB} -lm'
+  SOLVER='-DHAVE_PETSC ${PETSCFLAGS} ${PETSC_INCLUDE}'
+  LINKER='${CLINKER}'
+  PETSC_INCLUDE_MAKEFILE='include ${PETSC_DIR}/bmake/common/variables'
 
 else
 
   GETDP_DIRS="${GETDP_DIRS} Sparskit"
-  SOLVER='-DHAVE_SPARSKIT -DHAVE_ILU_FLOAT'
+  GETDP_LIBS="-Llib -lMain -lParser -lPost -lFunction -lIntegration -lGeoData -lDofData -lNumeric -lSparskit -lDataStr -lFMM"
+  SOLVER="-DHAVE_SPARSKIT -DHAVE_ILU_FLOAT"
   LINKER='${F77}'
   case "${UNAME}" in
     IRIX*)
@@ -3120,7 +3095,149 @@ else
       C_FLAGS="-g -O3 -DMSDOS"
       F77_FLAGS="-g -O1 -DMSDOS"
       ;;
+    Linux*)
+            case "${F77}" in
+        *pgf77*)
+          LINKER="${F77} -Mnomain"
+          GETDP_LIBS="Main/Main.o ${GETDP_LIBS}"
+          ;;
+      esac
+      ;;
   esac
+
+    ac_ext=f
+ac_compile='$F77 -c $FFLAGS conftest.$ac_ext >&5'
+ac_link='$F77 -o conftest$ac_exeext $FFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_f77_compiler_gnu
+
+  if test "x${LAPACK_PREFIX}" != "x"; then
+    LDFLAGS="-L${LAPACK_PREFIX} ${LDFLAGS}"
+  fi
+
+echo "$as_me:$LINENO: checking for dasum in -lblas" >&5
+echo $ECHO_N "checking for dasum in -lblas... $ECHO_C" >&6
+if test "${ac_cv_lib_blas_dasum+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lblas  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+      program main
+      call dasum
+      end
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_f77_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_blas_dasum=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_blas_dasum=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_blas_dasum" >&5
+echo "${ECHO_T}$ac_cv_lib_blas_dasum" >&6
+if test $ac_cv_lib_blas_dasum = yes; then
+  BLAS="yes"
+else
+  BLAS="no"
+fi
+
+  if test "x${BLAS}" = "xyes"; then
+    echo "$as_me:$LINENO: checking for dbdsqr in -llapack" >&5
+echo $ECHO_N "checking for dbdsqr in -llapack... $ECHO_C" >&6
+if test "${ac_cv_lib_lapack_dbdsqr+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-llapack -lblas $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+      program main
+      call dbdsqr
+      end
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_f77_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_lapack_dbdsqr=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_lapack_dbdsqr=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_lapack_dbdsqr" >&5
+echo "${ECHO_T}$ac_cv_lib_lapack_dbdsqr" >&6
+if test $ac_cv_lib_lapack_dbdsqr = yes; then
+  LAPACK="yes"
+else
+  LAPACK="no"
+fi
+
+    if test "x${LAPACK}" = "xyes"; then
+      C_FLAGS="${C_FLAGS} -DHAVE_LAPACK"
+      GETDP_DIRS="${GETDP_DIRS} Arpack"
+      GETDP_LIBS="${GETDP_LIBS} -lArpack"
+      if test "x${LAPACK_PREFIX}" = "x"; then
+        GETDP_LIBS="${GETDP_LIBS} -llapack -lblas"
+      else
+        GETDP_LIBS="${GETDP_LIBS} -L${LAPACK_PREFIX} -llapack -lblas"
+      fi
+    fi
+  fi
+  ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
 
 fi
 
@@ -3321,140 +3438,6 @@ echo "$as_me: error: Could not find GSL, aborting." >&2;}
    { (exit 1); exit 1; }; }
   fi
 fi
-
-ac_ext=f
-ac_compile='$F77 -c $FFLAGS conftest.$ac_ext >&5'
-ac_link='$F77 -o conftest$ac_exeext $FFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
-ac_compiler_gnu=$ac_cv_f77_compiler_gnu
-
-if test "x${LAPACK_PREFIX}" != "x"; then
-  LDFLAGS="-L${LAPACK_PREFIX} ${LDFLAGS}"
-fi
-
-echo "$as_me:$LINENO: checking for dasum in -lblas" >&5
-echo $ECHO_N "checking for dasum in -lblas... $ECHO_C" >&6
-if test "${ac_cv_lib_blas_dasum+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-lblas  $LIBS"
-cat >conftest.$ac_ext <<_ACEOF
-      program main
-      call dasum
-      end
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_f77_werror_flag"
-			 || test ! -s conftest.err'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; } &&
-	 { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  ac_cv_lib_blas_dasum=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-ac_cv_lib_blas_dasum=no
-fi
-rm -f conftest.err conftest.$ac_objext \
-      conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
-fi
-echo "$as_me:$LINENO: result: $ac_cv_lib_blas_dasum" >&5
-echo "${ECHO_T}$ac_cv_lib_blas_dasum" >&6
-if test $ac_cv_lib_blas_dasum = yes; then
-  BLAS="yes"
-else
-  BLAS="no"
-fi
-
-if test "x${BLAS}" = "xyes"; then
-  echo "$as_me:$LINENO: checking for dbdsqr in -llapack" >&5
-echo $ECHO_N "checking for dbdsqr in -llapack... $ECHO_C" >&6
-if test "${ac_cv_lib_lapack_dbdsqr+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-llapack -lblas $LIBS"
-cat >conftest.$ac_ext <<_ACEOF
-      program main
-      call dbdsqr
-      end
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_f77_werror_flag"
-			 || test ! -s conftest.err'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; } &&
-	 { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  ac_cv_lib_lapack_dbdsqr=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-ac_cv_lib_lapack_dbdsqr=no
-fi
-rm -f conftest.err conftest.$ac_objext \
-      conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
-fi
-echo "$as_me:$LINENO: result: $ac_cv_lib_lapack_dbdsqr" >&5
-echo "${ECHO_T}$ac_cv_lib_lapack_dbdsqr" >&6
-if test $ac_cv_lib_lapack_dbdsqr = yes; then
-  LAPACK="yes"
-else
-  LAPACK="no"
-fi
-
-  if test "x${LAPACK}" = "xyes"; then
-    C_FLAGS="${C_FLAGS} -DHAVE_LAPACK"
-    GETDP_DIRS="${GETDP_DIRS} Arpack"
-    GETDP_LIBS="${GETDP_LIBS} -lArpack"
-    if test "x${LAPACK_PREFIX}" = "x"; then
-      GETDP_LIBS="${GETDP_LIBS} -llapack -lblas"
-    else
-      GETDP_LIBS="${GETDP_LIBS} -L${LAPACK_PREFIX} -llapack -lblas"
-    fi
-  fi
-fi
-ac_ext=c
-ac_cpp='$CPP $CPPFLAGS'
-ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
-ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
-ac_compiler_gnu=$ac_cv_c_compiler_gnu
-
 
 if test "x$enable_debug" = "xyes"; then
   C_FLAGS="${C_FLAGS} -DHAVE_DEBUG_STACK"
